<?php
/**
 * 邮件发送记录管理器 - 内容模板
 * @var \Weline\Framework\View\Template $this
 */
?>
<link href='@static(Weline_Admin::assets/libs/sweetalert2/sweetalert2.min.css)' rel='stylesheet' type='text/css'/>
<link href="@static(Weline_Admin::/libs/jquery.mCustomScrollbar/jquery.mCustomScrollbar.css)" rel="stylesheet"/>

<div class="row">
    <div class="col-12">
        <div class="page-title-box d-sm-flex align-items-center justify-content-between">
            <h4 class="mb-sm-0"><?= __('邮件发送记录管理器') ?></h4>
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><span><?= __('系统') ?></span></li>
                    <li class="breadcrumb-item active"><?= __('邮件发送记录管理器') ?></li>
                </ol>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <template>Weline_Component::message.phtml</template>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title"><?= __('邮件发送记录管理器') ?>:
                    <lang>一共有</lang>
                    <var>total</var>
                    <lang>条数据</lang>
                </h4>

                <div class='table-responsive mCustomScrollbar' data-mcs-axis='x' data-mcs-theme='dark'>
                    <table class="table table-editable table-nowrap align-middle table-edits">
                        <thead>
                        <tr>
                            <th><lang>ID</lang></th>
                            <th><lang>模组</lang></th>
                            <th><lang>发送邮箱</lang></th>
                            <th><lang>发送者名称</lang></th>
                            <th><lang>接收者数据</lang></th>
                            <th><lang>主题</lang></th>
                            <th><lang>内容</lang></th>
                            <th><lang>创建时间</lang></th>
                            <th><lang>更新时间</lang></th>
                            <th><?= __('操作') ?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <foreach name="logs" item="log">
                            <tr>
                                <td>{{log.id}}</td>
                                <td>{{log.module}}</td>
                                <td>{{log.from_email}}</td>
                                <td>{{log.sender_name}}</td>
                                <td>
                                    {{log.to_email}}
                                    <if condition="log.cc !== '[]'">
                                        <lang>抄送：</lang>
                                        {{log.cc}}
                                    </if>
                                    <if condition="log.bcc  !== '[]'">
                                        <lang>密送：</lang>
                                        {{log.bcc}}
                                    </if>
                                </td>
                                <td>{{log.subject}}</td>
                                <td>
                                    <if condition="log.is_html=='1'">
                                        <span class=" badge bg-success">html</span>
                                        <else/>
                                        <span class=" badge bg-danger">text</span>
                                    </if>
                                    {{log.content}}
                                    <if condition="log.alt!=''">
                                        <br>
                                        <span class="badge bg-info">{{log.alt}}</span>
                                    </if>
                                </td>
                                <td>{{log.create_time}}</td>
                                <td>{{log.update_time}}</td>
                                <td>
                                    <form action="@backend-url('*/backend/log/delete')" method='post'>
                                        <input type='hidden' name='log_id' value='{{log.id}}'>
                                        <button class='btn btn-danger'>
                                            <lang>删除</lang>
                                        </button>
                                    </form>
                                    <form action="@backend-url('*/backend/log')" method='get'>
                                        <input type='hidden' name='log_id' value='{{log.id}}'>
                                        <button class='btn btn-primary'>
                                            <lang>阅读</lang>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        </foreach>
                        </tbody>
                    </table>
                    <div>
                        <var>pagination</var>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="@static(Weline_Admin::assets/libs/table-edits/build/table-edits.min.js)"></script>
<script src="@static(Weline_Admin::assets/js/pages/menus/table-editable.init.js)"></script>
<script src='@static(Weline_Admin::/libs/jquery.mCustomScrollbar/jquery.mCustomScrollbar.concat.min.js)'></script>
<script src='@static(Weline_Admin::assets/libs/sweetalert2/sweetalert2.min.js)'></script>
